### Task 14: Custom Swish Activation Layer

In [ ]:
#task14
import torch
import torch.nn as nn

# Sample Input
X = torch.randn(5)

# Custom Swish Activation
class Swish(nn.Module):

    def forward(self, x):
        return x * torch.sigmoid(x)

# Create Swish Layer
swish = Swish()

# Apply Swish
swish_output = swish(X)

# Compare with ReLU
relu = nn.ReLU()
relu_output = relu(X)

print("Input:")
print(X)

print("\nSwish Output:")
print(swish_output)

print("\nReLU Output:")
print(relu_output)

Input:
tensor([ 0.3339,  0.0188,  1.4955, -0.9395, -0.2527])

Swish Output:
tensor([ 0.1946,  0.0095,  1.2216, -0.2640, -0.1105])

ReLU Output:
tensor([0.3339, 0.0188, 1.4955, 0.0000, 0.0000])
